name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    
    - name: List Directory Structure
      run: ls -R

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: FixLanguagePackError
        path: ./bin

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: FixLanguagePackError
        path: ./bin

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/*
        tag_name: v${{ github.run_number }}
        title: Release ${{ github.run_number }}
        body: |
          Release ${{ github.run_number }} created by GitHub Actions
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
